// Copy this file to maps-api-key.js (gitignored, not committed) and fill in your own
// key for local testing. The deployed copy is generated by the GitHub Actions workflow
// from the GOOGLE_MAPS_API_KEY secret, not from this file.
window.GOOGLE_MAPS_API_KEY = "YOUR_GOOGLE_MAPS_API_KEY";
